# Generated by Django 5.0 on 2023-12-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveOfferView',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'offer',
                'managed': True,
            },
        ),
    ]
